include $(MAKE_VARS)

BOOTX64_TARGET = BOOTX64.EFI
BOOTX64_BUILD_DIR = $(BUILD_DIR)/bootloader/bootx64
BOOTX64_BUILD_TARGET = $(BOOTX64_BUILD_DIR)/$(BOOTX64_TARGET)

MDOSBOOT_TARGET = MDOSBOOT.EFI
MDOSBOOT_BUILD_DIR = $(BUILD_DIR)/bootloader/mdosboot
MDOSBOOT_BUILD_TAGET = $(MDOSBOOT_BUILD_DIR)/$(MDOSBOOT_TARGET)

KERNEL_TARGET := mdoskrnl.elf

TARGETS := $(TOPLEVEL_DIR)/entry/config.mk