#ifndef MDOS_MEMORY_TYPES_H
#define MDOS_MEMORY_TYPES_H

#include <stdint.h>

namespace MdOS::mem {
enum MemoryType : uint8_t{
	FREE_MEMORY,
	KERNEL_RESERVED_MEMORY,
	EFI_RESERVED_MEMORY,
	EFI_ACPI_RECLAIMABLE_MEMORY,
	EFI_RECLAIMABLE_MEMORY,
	KERNEL_ALLOCATED_MEMORY,
	DRIVER_ALLOCATED_MEMORY,
	USERSPACE_ALLOCATED_MEMORY,
	UNUSABLE_MEMORY,
	INVALID_TYPE,
};
}

#endif